# GENERATED by scripts/build-image.sh — do not edit here.
# Source: Containerfile.d/*.part   Profile: default   Components: indy10 mwajpeg djson
# Regenerate: scripts/build-image.sh --profile default

# component: base   (always — every profile starts here)
# desc: bake the Phase 3 prefix snapshot onto d7-base; PATH + DLL overrides for the IDE

FROM d7-base

# Bind-mount the snapshot (no COPY layer for 1.1 GB), swap it in for the empty
# booted prefix from d7-base, and fix ownership so wine's prefix check passes.
# W: -> /work gives the project mount a drive letter (dangling until run -v).
USER root
RUN --mount=type=bind,source=d7prefix.tar,target=/mnt/d7prefix.tar,z \
    set -eux; \
    rm -rf /home/dev/d7; mkdir -p /home/dev/d7; \
    tar xf /mnt/d7prefix.tar -C /home/dev/d7; \
    chown -R dev:dev /home/dev/d7; \
    ln -sf /work /home/dev/d7/dosdevices/w:; \
    chown -h dev:dev /home/dev/d7/dosdevices/w:; \
    ln -sfn /opt /home/dev/d7/drive_c/opt; \
    chown -h dev:dev /home/dev/d7/drive_c/opt; \
    install -d -o dev -g dev -m 700 /run/user/1000
USER dev

# Component installers drop dcus under /opt/<name>; the symlink above makes that
# same tree reachable as C:\opt\<name> so the IDE library path and headless
# `dcc32 -U` can use the Windows form.

# dcc32 / delphi32 on PATH for headless compiles; XDG_RUNTIME_DIR silences a wine
# warning on every invocation. WINEDLLOVERRIDES overrides d7-base's
# `mscoree,mshtml=`: .NET/Mono stays off (no wineboot prompt to fear — the prefix
# is already booted), but mshtml goes back to builtin, without which the D7 IDE
# throws at startup and quits (it hosts a WebBrowser on the Welcome page).
ENV PATH="/home/dev/d7/drive_c/Program Files/Borland/Delphi7/Bin:${PATH}" \
    XDG_RUNTIME_DIR=/run/user/1000 \
    WINEDLLOVERRIDES=mscoree=

# component: indy10
# desc: Indy 10.6.3.12 built for D7, swapped in for the bundled Indy 9 (IDE + headless)

# The two Indy generations can't coexist as loaded packages (same unit names), so
# swap-indy-ide.sh strips Indy 9 + the IntraWeb design package and registers Indy
# 10's. Headless `dcc32` uses $INDY10/dcu (put first on -U); the IDE gets it via
# the library path + Bin\*.bpl the swap sets. Baked so CI compiles don't rebuild
# Indy every run.
USER root
COPY --chown=dev:dev scripts/build-indy10.sh scripts/swap-indy-ide.sh /usr/local/bin/
RUN --mount=type=bind,source=vendor/indy10,target=/mnt/indy10,z \
    set -eux; \
    install -d -o dev -g dev /opt/indy10; \
    su -p -s /bin/bash dev -c ' \
      cp -a /mnt/indy10 /tmp/indy10 && \
      build-indy10.sh /tmp/indy10 /opt/indy10 && \
      swap-indy-ide.sh /opt/indy10 && \
      rm -rf /tmp/indy10 /opt/indy10/build'
USER dev
ENV INDY10=/opt/indy10

# component: mwajpeg
# desc: MWA Software JPEG Component Library v1.10.0 — TDBJPEGImage design pkg + dcus

# Additive component install (unlike indy10, nothing is removed): register the
# design package on the palette and drop the dcus at C:\opt\mwajpeg\dcu, on the
# IDE library path. Headless builds add that dir to -U.
USER root
COPY --chown=dev:dev scripts/install-mwajpeg.sh /usr/local/bin/
RUN --mount=type=bind,source=vendor/mwajpeg,target=/mnt/mwajpeg,z \
    set -eux; \
    install -d -o dev -g dev /opt/mwajpeg; \
    su -p -s /bin/bash dev -c 'install-mwajpeg.sh /mnt/mwajpeg /opt/mwajpeg'
USER dev
ENV MWAJPEG=/opt/mwajpeg

# component: djson
# desc: DJSON v1.0 — RTL-only JSON unit; dcu on the search path, no palette package

USER root
COPY --chown=dev:dev scripts/install-djson.sh /usr/local/bin/
RUN --mount=type=bind,source=vendor/djson,target=/mnt/djson,z \
    set -eux; \
    install -d -o dev -g dev /opt/djson; \
    su -p -s /bin/bash dev -c 'install-djson.sh /mnt/djson /opt/djson'
USER dev
ENV DJSON=/opt/djson

# component: footer   (always — closes the image)

CMD ["wine", "explorer", "/desktop=d7,1600x1000", "C:\\Program Files\\Borland\\Delphi7\\Bin\\delphi32.exe"]
