#!/usr/bin/env bash
# Assemble the one D7 workstation image (d7-dev) from component fragments.
#
#   build-image.sh [--profile NAME] [--with C]... [--without C]...
#                  [--tag TAG] [--out FILE] [--print | --check]
#                  [-- PODMAN_BUILD_ARGS...]
#
# Components live in Containerfile.d/NN-<name>.part; the NN prefix sets install
# order. A profile (profiles/NAME.conf, default `default`) lists which components
# to install, one per line. --with / --without adjust that set. The rendered
# Containerfile is written to ./Containerfile (committed as the default-profile
# reference) unless --out; --print writes nothing and dumps to stdout; --check
# fails if ./Containerfile is stale.
set -euo pipefail
cd "$(dirname "$0")/.."

FRAG=Containerfile.d
profile=default
tag=d7-dev
out=
mode=build
with=() without=() passthru=()

while [ $# -gt 0 ]; do
  case $1 in
    --profile) profile=$2; shift 2 ;;
    --with)    with+=("$2"); shift 2 ;;
    --without) without+=("$2"); shift 2 ;;
    --tag)     tag=$2; shift 2 ;;
    --out)     out=$2; shift 2 ;;
    --print)   mode=print; shift ;;
    --check)   mode=check; shift ;;
    --)        shift; passthru=("$@"); break ;;
    *) echo "build-image.sh: unknown arg: $1" >&2; exit 2 ;;
  esac
done

pf="profiles/$profile.conf"
[ -f "$pf" ] || { echo "build-image.sh: no such profile: $pf" >&2; exit 2; }

# ./Containerfile is committed as the default-profile render; any other profile
# writes to .build/ so it can't clobber it.
if [ -z "$out" ]; then
  if [ "$profile" = default ]; then out=Containerfile
  else out=".build/Containerfile.$profile"; mkdir -p .build; fi
fi

want=()
in_want() { local c; for c in ${want[@]+"${want[@]}"}; do [ "$c" = "$1" ] && return 0; done; return 1; }
add()     { in_want "$1" || want+=("$1"); }

while read -r line; do
  line=${line%%#*}; line=$(echo "$line" | tr -d '[:space:]')
  [ -n "$line" ] && add "$line"
done < "$pf"
for c in ${with[@]+"${with[@]}"};    do add "$c"; done
for c in ${without[@]+"${without[@]}"}; do
  keep=(); for k in ${want[@]+"${want[@]}"}; do [ "$k" = "$c" ] || keep+=("$k"); done
  want=(${keep[@]+"${keep[@]}"})
done

parts=()
for c in ${want[@]+"${want[@]}"}; do
  match=("$FRAG"/[0-9]*-"$c".part)
  [ -f "${match[0]}" ] || { echo "build-image.sh: no fragment for component '$c'" >&2; exit 2; }
  parts+=("${match[0]}")
done
if [ ${#parts[@]} -gt 0 ]; then
  mapfile -t parts < <(printf '%s\n' "${parts[@]}" | sort)
fi

render() {
  printf '# GENERATED by scripts/build-image.sh — do not edit here.\n'
  printf '# Source: %s/*.part   Profile: %s   Components: %s\n' "$FRAG" "$profile" "${want[*]:-none}"
  printf '# Regenerate: scripts/build-image.sh --profile %s\n' "$profile"
  local f
  for f in "$FRAG"/00-*.part ${parts[@]+"${parts[@]}"} "$FRAG"/99-*.part; do
    printf '\n'
    cat "$f"
  done
}

case $mode in
  print) render ;;
  check)
    tmp=$(mktemp)
    render > "$tmp"
    if diff -u "$out" "$tmp"; then
      echo "$out is up to date (profile: $profile)"
      rm -f "$tmp"
    else
      rm -f "$tmp"
      echo "build-image.sh: $out is stale — run: scripts/build-image.sh --profile $profile" >&2
      exit 1
    fi ;;
  build)
    render > "$out"
    echo ">>> wrote $out  (profile: $profile, components: ${want[*]:-none})"
    set -x
    exec podman build -f "$out" -t "$tag" --security-opt label=disable \
         ${passthru[@]+"${passthru[@]}"} . ;;
esac
